# Generated by Django 3.0.6 on 2020-05-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default='product_default.jpg', upload_to='product_pics'),
        ),
    ]
