# Generated by Django 3.0.6 on 2020-06-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_loyaltycard_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loyalty_card',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoyaltyCard',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
